### ISSUE TITLE
Relationship includes with multiple words don't work with custom key_format

### ISSUE THREAD

**Issue by Subtletree** [jsonapi-rb/jsonapi-serializable#93] opened 2017-11-23 22:11 UTC
If a custom key_format is specified:
```
  extend JSONAPI::Serializable::Resource::KeyFormat
  key_format ->(k) { k.to_s.camelize(:lower) }
```
Requests such as `/users?include=new_posts` with multiple word relationships result in the multi word relationship not being included.

[jsonapi_related]( https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/lib/jsonapi/serializable/resource.rb#L74-L78) compares the client formatted includes to [relationship_blocks](https://github.com/jsonapi-rb/jsonapi-serializable/blob/3fb91d67b3d18011c109cfeb65173950e296a85f/lib/jsonapi/serializable/resource/dsl.rb#L158) which is overridden by `KeyFormat`. So multi word relations will never match.

The client cannot pass in formatted keys either e.g `/users?include=newPosts` as the `newPosts` relationship is not found

**Comment by beauby** [comment] 2017-11-24 08:36
The expected behavior is that the client should only care about the formatted keys. 
Would you mind providing a regression test?

**Comment by beauby** [comment] 2017-12-06 17:32
Closing this as it seems to be a usage issue. Feel free to reopen if needed.

**Closed by beauby** 2017-12-06 17:32 UTC
