### ISSUE TITLE
Key formatting doesn't apply to hash attributes or to meta hash

### ISSUE THREAD

**Issue by ezekg** [jsonapi-rb/jsonapi-serializable#50] opened 2016-12-30 18:26 UTC
## Example serializer
```ruby
require "jsonapi/serializable/resource/key_transform"

class SerializableResource < JSONAPI::Serializable::Resource
  prepend JSONAPI::Serializable::Resource::KeyTransform
  self.key_transform = -> (key) { key.to_s.camelize :lower }

  attribute :attr do
    { a_key: "a value" }
  end
  
  meta do
    { a_key: "a value" }
  end
end
```

## Expected serialization
```json
{
  "data": {
    "type": "resources",
    "id": 1,
    "attributes": {
      "attr": { "aKey": "a value" }
    },
    "meta": {
      "aKey": "a value"
    }
}
```

## Actual serialization
```json
{
  "data": {
    "type": "resources",
    "id": 1,
    "attributes": {
      "attr": { "a_key": "a value" }
    },
    "meta": {
      "a_key": "a value"
    }
}
```

As always, I can make create a PR to fix the issue if you'd like. 👍

**Comment by beauby** [comment] 2016-12-31 15:08
Hi Zeke, thanks for watching out!

In this case, it is actually by design: only the attribute/relationship
keys are being formatted.
The rationale is that
1. Modifying explicitly-supplied data would break POLS IMO, and
2. Recursively traversing nested hashes structures would incur a perf drop
(currently, the actual string transformations happen at definition time, so
no perf is lost during serialization, which is only possible since the keys
are known at définition time, which would not be the case for the behavior
you describe), and finally,
3. Recursively transforming keys is not clearly defined as some people
would expect hashes nested inside an array to be transversed as well, while
some other people may not.

Could you expand a bit on your use-case so that we can find a satisfying
solution? I suspect you're exposing a serialized resource as an attribute
of an other?

Cheers,

Lucas

**Comment by ezekg** [comment] 2016-12-31 18:40
I figured it was done for performance reasons. I have a few json columns in my database (Postgres), mostly for attaching consumer-defined metadata, e.g. like Stripe allows. All of my responses contain camel-cased keys, as the API is primarily built to be consumed in JS envs. I'm currently doing the transformations manually in each serializer, so if it's by design I'll just keep doing that.

Appreciate the explanation. 👍

**Comment by beauby** [comment] 2017-02-17 02:02
Closing this for now, according to the above explanation.
Best workaround I can think of at the moment:
```ruby
# Define 
module SerializationHelpers
  module_function
  def camel_case(attr)
    # do your biddings here
  #
end

class SerializableFoo
  attribute(:foo) { camel_case(@object.foo) }
end
```

**Closed by beauby** 2017-02-17 02:02 UTC
